language: python

python:
  - 2.7

before_script:
  - bundle install
  - npm install -g npm@2
  - ./node_modules/.bin/bower install
  - cd test
  - ../node_modules/.bin/bower install
  - cd ..

install: "pip install -r requirements.txt"

script:
  - python manage.py test
  - ./node_modules/.bin/grunt test
  - ./node_modules/.bin/grunt
